version: 2.1
jobs:
  pe_build:
   docker:
      - image: zhz1021/ubuntu-android-buildbot:20.04-pe
   resource_class: 2xlarge
   steps:
      - run:
          name: Start to build
          command: |
           git config --global user.name "zhz8888"
           git config --global user.email "zhz1021@gmail.com"
           repo init -u https://github.com/PixelExperience/manifest.git -b twelve-plus --depth 1
           repo sync -c --force-sync --no-clone-bundle --no-tags
           git clone https://github.com/coolscode/patches.git --depth 1
           bash patches/apply.sh pe
           git clone https://jihulab.com/zhz8888-Developing/land/local_manifests.git -b pe-twelve --depth 1 .repo/local_manifests
           repo sync -c --force-sync --no-clone-bundle --no-tags
           source build/envsetup.sh
           lunch aosp_land-userdebug
           mka bacon | tee -a build-land.log
      - store_artifacts:
          path: /buildout/repo-*.log
          when: always
      - store_artifacts:
          path: /buildout/build-*.log
          when: always
      - store_artifacts:
          path: /buildout/PixelExperience-*.zip
      - store_artifacts:
          path: /buildout/PixelExperience-*.sha256sum
      - store_artifacts:
          path: /buildout/boot.img
      - store_artifacts:
          path: /buildout/recovery.img
      - store_artifacts:
          path: /buildout/*eng*.zip
workflows:
  version: 2.1
  build:
    jobs:
      - pe_build
